name: fevo-dev

services:
  postgres:
    image: postgres:16
    container_name: fevo-dev
    restart: always
    environment:
      - POSTGRES_USER=fevo
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fevo
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "54320:5432"
volumes:
  database: